- project:
    templates:
      - check-requirements
      - horizon-non-primary-django-jobs
      - horizon-nodejs14-jobs
      - openstack-cover-jobs-horizon
      - openstack-lower-constraints-jobs
      - openstack-python3-xena-jobs-horizon
      - release-notes-jobs-python3
    check:
      jobs:
        - murano-dashboard-sanity-check

- job:
    name: murano-dashboard-sanity-check
    parent: legacy-dsvm-base
    run: playbooks/legacy/murano-dashboard-sanity-check/run.yaml
    post-run: playbooks/legacy/murano-dashboard-sanity-check/post.yaml
    irrelevant-files:
      - ^(test-|)requirements.txt$
      - ^setup.cfg$
      - ^doc/.*$
      - ^.*\.rst$
      - ^releasenotes/.*$
      - ^muranodashboard/locale/.*$
      - ^muranodashboard/tests/unit/.*$
    voting: false
    timeout: 10800
    required-projects:
      - openstack/devstack-gate
      - openstack/heat
      - openstack/murano
      - openstack/murano-dashboard
      - openstack/python-heatclient
      - openstack/python-muranoclient
      - openstack/horizon
      - openstack/heat-dashboard
