AD_NAME = 'Active Directory'
IIS_NAME = 'IIS'
ASP_NAME = 'ASP.NET Application'
IIS_FARM_NAME = 'IIS Farm'
ASP_FARM_NAME = 'ASP.NET Farm'

SERVICE_NAMES = (AD_NAME, IIS_NAME, ASP_NAME, IIS_FARM_NAME, ASP_FARM_NAME)
